spring:
  datasource:
    url: jdbc:h2:mem:test

  liquibase:
    contexts: dev
    change-log: classpath:database/changelog/master.xml
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true